### ISSUE TITLE
Example schema doesn't contain "handlers" section.

### ISSUE THREAD

**Issue by pawelaugustyn** [aws-cloudformation/cloudformation-cli-go-plugin#114]
According to code present in [cloudformation-cli](https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/data/schema/provider.definition.schema.v1.json), _handlers_ section is compulsory and each handler must contain at least one permission.
In current form example is not working (Unrecognized Type: _Example::GitHub::Repo_), after adding _handlers_ section in schema file CloudFormation recognizes newly added type.

**Comment by brianterry** [comment]
Looks like the schema is out of date. I'll create a PR.

**Comment by stilvoid** [comment]
I can't replicate this. When I generate a new schema file with `cfn init`, it includes `handlers`.

**Comment by stilvoid** [comment]
> I can't replicate this. When I generate a new schema file with `cfn init`, it includes `handlers`.

Ignore that, I misunderstood. You mean the example code in the `example` folder :)

**Comment by stilvoid** [comment]
Fixed in #125
