### ISSUE TITLE
A `number` property generates as `*float`

### ISSUE THREAD

**Issue by gbernady** [aws-cloudformation/cloudformation-cli-go-plugin#121]
With the following properties block in the provider schema:
```json
{
    "properties": {
        "ResourceID": {
            "description": "Unique identifier of the resource",
            "type": "string"
        },
        "Foo": {
            "description": "Some number property",
            "type": "number",
            "default": 42
        }
    }
}
```
the generated model is
```go
package resource

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	ResourceID *string `json:",omitempty"`
	Foo        *float  `json:",omitempty"`
}
```

The model does not compile, because there is no `float` type in Go. I guess it should be `float64`.

**Comment by jotompki** [comment]
Thanks for bringing this up!
Looks like we just need to change [this.](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/blob/master/python/rpdk/go/resolver.py#L7)

**Comment by brianterry** [comment]
Thank you for spotting this issue. I'm working on a PR now and it will be up shortly.

**Comment by brianterry** [comment]
Thank you for spotting this issue. I'm working on a PR now and it will be up shortly.

**Comment by stlava** [comment]
Same thing for `integer` as well. `{'status': 'FAILED', 'errorCode': 'GeneralServiceException', 'message': 'Unable to complete request: interface conversion: interface {} is float64, not string'}`
