### ISSUE TITLE
TypeError: argument of type 'WindowsPath' is not iterable

### ISSUE THREAD

**Issue by kacpernzk1** [aws-cloudformation/cloudformation-cli-go-plugin#123]
Project fails on cfn generate in windows 10 (, works on MacOS)

cfn 0.1.2
[rpdk.log](https://github.com/aws-cloudformation/cloudformation-cli/files/4243485/rpdk.log)

**Comment by brianterry** [comment]
This is a  different issue and not related to #87. This is a bug in core python. Looks like this  [issue](https://bugs.python.org/issue33617) was fixed in python 3.8. So upgrading to Python 3.8 should fix the issue.

**Comment by kacpernzk1** [comment]
I agree that python 3.8 is required. I used WSL (ubuntu 18.04 LTS)  with VS Code (https://code.visualstudio.com/docs/remote/wsl)

First issue: some import paths in generated golang code got '\' separator (other keep '/')
It looks stricly connected with python as @brianterry mentions.

**Comment by brianterry** [comment]
So does upgrading fix the problem or do we need to keep this issue open?

**Comment by kacpernzk1** [comment]
I'm affraid it didnt. Just checked on Windows using Python 3.8.1. cfnGenerate is failing with rpdk.log 
[rpdk - Copy.log](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/files/4265680/rpdk.-.Copy.log)

I've tried to update import path in rpdk-config to windows separator but it fails with "json.decoder.JSONDecodeError: Invalid \escape"

As i found workaround with WSL i dont have priority on this one. 
In my opinion upgrading python to 3.8 on Windows is not enough - but this might be project settins issue as well (which works on mac however)

**Comment by mtttcgcg** [comment]
Same error on Windows with cfn 0.1.5.
