### ISSUE TITLE
cfn test errors when using integer property

### ISSUE THREAD

**Issue by stlava** [aws-cloudformation/cloudformation-cli-go-plugin#124]
Here is our property:
```
        "AutoResolveTimeout": {
            "description": "Auto resolve timeout of this Pagerduty service.",
            "type": "integer"
        },
```

When running the `cfn test` we get: `Unable to complete request: interface conversion: interface {} is float64, not string`

**Comment by stilvoid** [comment]
I can't replicate this using a trivial example schema. Can you share some of the handler code?

**Comment by ctrombley** [comment]
+1 on this issue with very simple handlers that match the generated example code like so:

```go
response := handler.ProgressEvent{
    OperationStatus: handler.Success,
    Message:         "Create complete",
    ResourceModel:   currentModel,
}

return response, nil
```

I also get a similar issue when using any `boolean` types in my schema.  Use of the following schema param:

```json
        "IgnoreOverlap": {
          "description": "description",
          "type": "boolean"
        },
```

leads to the following error when running `cfn test`:

```
Unable to complete request: interface conversion: interface {} is bool, not string
```
