### ISSUE TITLE
Failure handling not consistent across java and go

### ISSUE THREAD

**Issue by stlava** [aws-cloudformation/cloudformation-cli-go-plugin#132]
In the java implementation the developer is able to call `ProgressEvent.failed` with a `ProgressEvent` with additional details like status code and message[1]. However, in Go the returned `ProgressEvent` is thrown out and only the `error` is sent back [2].

[1] https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/master/src/main/java/software/amazon/cloudformation/proxy/ProgressEvent.java#L83-L99
[2] https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/blob/d8ba82c35d5d38ad19a58fc274c1658ee9bf5296/python/rpdk/go/templates/main.go.tple#L66-L69

**Comment by brianterry** [comment]
Hello,
Thank you for bring up this issue. The Go plug works just like the Java version. 

Returning an error from handler is just a short cut to return a standard `handler.NewFailedEvent`.
https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/blob/d8ba82c35d5d38ad19a58fc274c1658ee9bf5296/cfn/handler/event.go#L54

If you want to return a ProgressEvent with additional details like status code and message, simply return something like this:

```
response := handler.ProgressEvent{
		OperationStatus:  handler.Failed,
		HandlerErrorCode: errorCode,
		ResourceModel:    currentModel,
		Message:          "Message information",
	},nil
```

**Comment by stlava** [comment]
That sounds good, can the docs/examples be updated to that there are 2 ways to return errors. If you want a custom response don't return the error.

**Comment by brianterry** [comment]
Yes, we plan to release more examples showing how to return a custom response.

**Comment by brianterry** [comment]
Closing this issue for now.
