### ISSUE TITLE
Errors from Unstringify are ignored

### ISSUE THREAD

**Issue by gbernady** [aws-cloudformation/cloudformation-cli-go-plugin#137]
When passing invalid properties to the provider, errors from `encoding.Unstringify()` are ignored and the handler is invoked with partially empty model struct.

I traced the issue to `encoding.Unmarshal` calling simply

```go
Unstringify(dataMap, v)
```

instead of something like

```go
err = Unstringify(dataMap, v)
if err != nil {
	return err
}
```

**Comment by brianterry** [comment]
Thank you @gbernady for bring this to our attention. I agree `Unstringify` should return an error when given invalid properties.
