### ISSUE TITLE
Slices of structs are not properly unmarshalled

### ISSUE THREAD

**Issue by n-apalm** [aws-cloudformation/cloudformation-cli-go-plugin#138]
Slices get sent over properly to the plugin, but unmarshalling fails to translate the list of structs properly. Each field just gets populated with the zero value.

Sent:
`"Rules": [
        {
          "/Delay": 5,
          "/Targets": [
            {
              "/Id": "AO24E5Y",
              "/Type": "type_reference"
            }
          ]
        }
]`

Received:
`[{Delay:<nil> Targets:[]}]`

**Comment by kadrach** [comment]
In case you are running into this issue during contract testing, a similar issue I had a few days ago was fixed by da8ed789cac717d33ee20c9ec4ed6dc6ec0d7700.

**Comment by brianterry** [comment]
Fixed by #131. Closing issue.
