### ISSUE TITLE
Idempotency token / client request token in go plugin?

### ISSUE THREAD

**Issue by x6j8x** [aws-cloudformation/cloudformation-cli-go-plugin#148]
The resource provider handler contract talks about an "idempotency token" (https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test-contract.html), for instance here:

> A create handler MUST be idempotent. A create handler MUST NOT create multiple resources given the same idempotency token.

This token doesn't seem to be exposed in the Go plugin. In Java there's a clientRequestToken field - https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/e83e79fef6d33042105ebc368839d941bab3faa5/src/main/java/software/amazon/cloudformation/proxy/ResourceHandlerRequest.java#L34 - which I assume fulfils this function.

**Comment by ammokhov** [comment]
@x6j8x impotency token is the primary identifier of the resource. It could be service generated, unique user entry or if not provided should be generated similarly to [java](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/commit/953665c7e844615447e16840e8e93338068c1080) or [python](https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/commit/2306d7e9792a35791c293195e8ce99ead9e9b09d) plugins;

Client request token is used by the identifier utils module and provides necessary randomization per each request (unique hash part) - `stackname-logicalid-hash`

**Comment by ammokhov** [comment]
@x6j8x since it's a bit broader than just adding ClientRequestToken we will track this issue under #176 and close this one
