### ISSUE TITLE
No way to report status messages back to user

### ISSUE THREAD

**Issue by aidansteele** [aws-cloudformation/cloudformation-cli-go-plugin#152]
In the progress event payloads, there's a field named `Message` but it looks like this doesn't appear anywhere except in the CloudWatch Logs for the resource type. I was expecting that it would appear in the CloudFormation stack events.

Is this a regression? I haven't used the library for a few months now, but I could have sworn it used to have this functionality.  Was this what [`RecordHandlerProgress`](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_RecordHandlerProgress.html) used to do? I see that it's no longer used in the RPDK since this commit bringing in protocol v2: https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/commit/c159be97639a5393e9bc3cc683ddd8b125f85ae1#diff-b5bc110a4f0f580507ee6787589937beL34

Was this intentional? Should there be a way to get status messages to appear in the stack events API? It would be very useful to indicate to the user what the resource provider is doing during a slow create/update.

**Comment by ammokhov** [comment]
> In the progress event payloads, there's a field named `Message` but it looks like this doesn't appear anywhere except in the CloudWatch Logs for the resource type. I was expecting that it would appear in the CloudFormation stack events.
> 
> Is this a regression? I haven't used the library for a few months now, but I could have sworn it used to have this functionality. Was this what [`RecordHandlerProgress`](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_RecordHandlerProgress.html) used to do? I see that it's no longer used in the RPDK since this commit bringing in protocol v2: [c159be9#diff-b5bc110a4f0f580507ee6787589937beL34](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/commit/c159be97639a5393e9bc3cc683ddd8b125f85ae1#diff-b5bc110a4f0f580507ee6787589937beL34)
> 
> Was this intentional? Should there be a way to get status messages to appear in the stack events API? It would be very useful to indicate to the user what the resource provider is doing during a slow create/update.

The cloudformation changed provider protocol which no longer uses cloudwatch to schedule re-invocations; currently, message are only surfaced on failed events; we might include it in the future for other events too;
