### ISSUE TITLE
cfn submit: No Go executable was found.

### ISSUE THREAD

**Issue by rclark** [aws-cloudformation/cloudformation-cli-go-plugin#171]
When I run `cfn submit --dryrun`:

```
root ➜ /workspaces/bucket/logs (master ✗) $ cfn submit --dry-run
No Go executable was found.
Please run 'make' or the equivalent command in your IDE to compile and package the code.
```

This makes me think "why is there no Go executable?

```
root ➜ /workspaces/bucket/logs (master ✗) $ which go
/usr/local/go/bin/go
root ➜ /workspaces/bucket/logs (master ✗) $ go version
go version go1.15.2 linux/amd64
```

But in reality, this is just a misleading error message.

https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/blob/6f630e721b2bf3b1121a7c05ea328295bb39fa6f/python/rpdk/go/codegen.py#L224-L232

This isn't that the "Go executable" isn't found, its trying to say that it expects you to use `make` to bundle the resource provider first. The error message should probably be more like

```py
    def _find_exe(project):
        exe_glob = list((project.root / "bin").glob("{}".format("handler")))
        if not exe_glob:
            LOG.debug("No Go executable match")
            raise GoExecutableNotFoundError(
                "You must build the handler before running cfn-submit.\n"
                "Please run 'make' or the equivalent command "
                "in your IDE to compile and package the code.\n"
            )
```

... or better yet, the `cfn submit` command should, in fact, build for you [like the documentation implies](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-cli-submit.html).

> Packaging up the resource project files and uploading them to CloudFormation.

**Comment by omkhegde** [comment]
Hi @rclark , thank you for your submission. I have created the PR to update the error message. I think `cfn submit` is working as expected, since as the document mentions, it packages up the resource project files by creating the .zip file for the generated resource code, and `cfn generate` is needed to generate code based on the project and resource type schema.

**Comment by rclark** [comment]
Thanks -- I do think it might be worth considering the desired interface and the relationships between

- `cfn generate`
- `make build`
- `cfn submit`

As someone trying to learn the procedure [based on the documented walkthrough](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-walkthrough.html), I certainly expected `cfn submit` to handle the compilation step. There's obviously a documentation/interface challenge here, since a walkthrough for one language may need a compilation step and another might not.

**Comment by brianterry** [comment]
Hi @rclark that's a good point. However, if submit compiled the executable, that would limit compilation to the local machine. Some developers (including myself) use a Docker container to compile my Go files.

**Comment by brianterry** [comment]
@rclark, we merged a fix that update error message. Closing the issue for now.
