### ISSUE TITLE
FAILED - KeyError: 'status'

### ISSUE THREAD

**Issue by ggiallo28** [aws-cloudformation/cloudformation-cli-go-plugin#174]
I have currently installed this:

- cloudformation-cli==0.1.10
- cloudformation-cli-go-plugin==2.0.1

whit this implementation 

	response := handler.ProgressEvent{
		OperationStatus: handler.Success,
		Message:         "Create complete",
		ResourceModel:   currentModel,
	}

	return response, nil

I get the below error, how can i Fix it?
```
============================short test summary info ===================================
FAILED handler_create.py::contract_create_delete - KeyError: 'status'
FAILED handler_create.py::contract_invalid_create - KeyError: 'status'
FAILED handler_read.py::contract_read_without_create - KeyError: 'status'
FAILED handler_update_invalid.py::contract_update_create_only_property - UnboundLocalError: local variable 'created_model' referenced before as...
FAILED handler_update_invalid.py::contract_update_non_existent_resource - KeyError: 'status'
ERROR handler_create.py::contract_create_duplicate - KeyError: 'status'
ERROR handler_create.py::contract_create_read_success - KeyError: 'status'
ERROR handler_create.py::contract_create_list_success - KeyError: 'status'
ERROR handler_delete.py::contract_delete_read - KeyError: 'status'
ERROR handler_delete.py::contract_delete_list - KeyError: 'status'
ERROR handler_delete.py::contract_delete_update - KeyError: 'status'
ERROR handler_delete.py::contract_delete_delete - KeyError: 'status'
ERROR handler_delete.py::contract_delete_create - KeyError: 'status'
ERROR handler_update.py::contract_update_read_success - KeyError: 'status'
ERROR handler_update.py::contract_update_list_success - KeyError: 'status'
```

**Comment by omkhegde** [comment]
Hi @ggiallo28 , we have released a new version 2.0.2 of the Go plugin which includes fixes for the contract test errors that you encountered: https://pypi.org/project/cloudformation-cli-go-plugin/2.0.2/ .

**Comment by ggiallo28** [comment]
@omkhegde same problem with version 2.0.2.

1. Generate Example and build:
- Test: KeyError: 'date-time'

2. Remove "format": "date-time" in Schema.json
- Test: KeyError: 'status'
{'errorType': 'baseError', 'errorMessage': 'Validation: Failed Validation\ncaused by: ResourceType: zero value'}

3. Uncomment example implementation in resource.go
- Test: KeyError: 'status'
{'errorType': 'baseError', 'errorMessage': 'Validation: Failed Validation\ncaused by: ResourceType: zero value'}

What is wrong?
I'm using the default generated schema.json

$ pip freeze
attrs==20.2.0
boto3==1.16.0
botocore==1.19.0
certifi==2020.6.20
chardet==3.0.4
cloudformation-cli==0.1.12
cloudformation-cli-go-plugin==2.0.2
colorama==0.4.4
docker==4.3.1
hypothesis==5.37.3
idna==2.10
importlib-metadata==2.0.0
iniconfig==1.1.1
Jinja2==2.11.2
jmespath==0.10.0
jsonschema==3.2.0
MarkupSafe==1.1.1
packaging==20.4
pluggy==0.13.1
py==1.9.0
pyparsing==2.4.7
pyrsistent==0.17.3
pytest==6.1.1
pytest-localserver==0.5.0
pytest-random-order==1.0.4
python-dateutil==2.8.1
PyYAML==5.3.1
requests==2.24.0
s3transfer==0.3.3
semver==2.12.0
six==1.15.0
sortedcontainers==2.2.2
toml==0.10.1
urllib3==1.25.11
websocket-client==0.57.0
Werkzeug==1.0.1
zipp==3.3.1

**Comment by omkhegde** [comment]
@ggiallo28 what version of the plugin is being used in the go.mod file? You shouldn't be seeing  `ResourceType: zero value'}`, since it was made optional by a recent commit (https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/commit/334098076d291029c92ba9dc775a4a7790ea1f25)

**Comment by ggiallo28** [comment]
go 1.13

require github.com/aws-cloudformation/cloudformation-cli-go-plugin v1.0.2

**Comment by omkhegde** [comment]
Great! Thank you for the update. Closing the issue.
