### ISSUE TITLE
Set GOARCH=amd64 in build

### ISSUE THREAD

**Issue by rclark** [aws-cloudformation/cloudformation-cli-go-plugin#194]
https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/blob/d23e052b5de23d9026d9e39c5f488279ea7900a4/python/rpdk/go/templates/makebuild#L7

On arm64 systems (e.g. new M1 Macs) this results in a binary built for the wrong architecture. Adding `GOARCH=amd64` would make sure that the binaries are appropriate for Lambda runtimes.

**Comment by mlafeldt** [comment]
Our current workaround is to pass GOARCH to makebuild:

```make
build:
	env GOARCH=amd64 TAGS=logging make -f makebuild
```

Of course, a real fix would be nice!

**Comment by mmaeng** [comment]
Implemented in PR #209
