### ISSUE TITLE
running unit tests deletes `/tmp` directory

### ISSUE THREAD

**Issue by KevinPike** [aws-cloudformation/cloudformation-cli-go-plugin#197]
Running the unit tests invoke [`scrubFiles`](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/blob/d23e052b5de23d9026d9e39c5f488279ea7900a4/cfn/cfn.go#L106) which deletes `/tmp` directory on the users computer.

**Comment by kddejong** [comment]
I removed this code.  It no longer does.
