### ISSUE TITLE
Support type configuration

### ISSUE THREAD

**Issue by wbingli** [aws-cloudformation/cloudformation-cli-go-plugin#200]
Type configuration allows to configure a resource type such as credential  and dynamic reference out of resource properties.  

Java plugin has supported it: https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/370

Need support it in Go plugin.

**Comment by kddejong** [comment]
This should be released and ready.  Give it a try and let us know if you have any issues.
