### ISSUE TITLE
Accessing primaryIdentifier in stack Outputs?

### ISSUE THREAD

**Issue by msummers-nr** [aws-cloudformation/cloudformation-cli-go-plugin#207]
I have a `readOnlyProperties` primaryIdentifier (`Guid`) I'm trying to access in a stack's `Outputs`:
```
Outputs:
  CustomResourceAttribute1:
    Value: !GetAtt  Resource1.Guid
```
The stack fails with 
```
Unable to retrieve Guid attribute for NewRelic::CloudFormation::Workloads, with error message Unable to complete request: runtime error: invalid memory address or nil pointer dereference. Rollback requested by user.
```
If I remove the `Outputs` section the stack completes successfully and the resource is created.

FWIW the custom resource passes the `test-type` tests without any problem.

Any pointers or suggestions would be appreciated.

**Comment by brianterry** [comment]
HI!
Are you returning the `Guid` in the read handler?

**Comment by msummers-nr** [comment]
All handlers return the guid, it's the primary identifier

**Comment by msummers-nr** [comment]
The root cause here was bad code. The resource passed the Contract tests however that is not a guarantee of CF compatibility.
