### ISSUE TITLE
cmd/resource/config.go:15:16: req.UnmarshalTypeConfig undefined

### ISSUE THREAD

**Issue by ivan-savciuc** [aws-cloudformation/cloudformation-cli-go-plugin#215]
We are trying to create the first CF resource using Golang Plugin but getting stuck with this error: 
```
env GOOS=linux go build -ldflags="-s -w" -o bin/handler cmd/main.go
cmd/resource/config.go:15:16: req.UnmarshalTypeConfig undefined (type handler.Request has no field or method UnmarshalTypeConfig)
```

`cfn generate` generates a resource template with the following config.go: 
```
// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

import "github.com/aws-cloudformation/cloudformation-cli-go-plugin/cfn/handler"

// TypeConfiguration is autogenerated from the json schema
type TypeConfiguration struct {
}

// Configuration returns a resource's configuration.
func Configuration(req handler.Request) (*TypeConfiguration, error) {
	// Populate the type configuration
	typeConfig := &TypeConfiguration{}
	if err := req.UnmarshalTypeConfig(typeConfig); err != nil {
		return typeConfig, err
	}
	return typeConfig, nil
}
```

And as you can tell from the build error, there is no such method: `UnmarshalTypeConfig`.
What would be a workaround or fix that issue? 

*UPDATE:* I'm now using the latest master instead of the last release to continue work.

**Comment by ivan-savciuc** [comment]
A new release would fix that issue. The last was two years ago.

**Comment by dewan-ahmed** [comment]
Hi @ivan-savciuc I see that https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/releases/tag/v1.1.0 was released 5 days ago. Does this resolve the issue?

**Comment by ivan-savciuc** [comment]
Hi, Yes it does, though there are few more. I will open them shortly.

**Comment by dewan-ahmed** [comment]
Hi @ivan-savciuc if you have opened the other GitHub issues, could you please link them here and we can then check with Eric's team on a resolution? Thank you.

**Comment by kddejong** [comment]
Thanks @ivan-savciuc .  Let us know what other issues you are having.  Thanks.
