### ISSUE TITLE
31 Dec 2023 Go Lambda Migration

### ISSUE THREAD

**Issue by msummers-nr** [aws-cloudformation/cloudformation-cli-go-plugin#228]
Has anyone been able to get their CFN custom resource to work with the [changes required by 31 Dec 2023](https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/)? 

I changed the `Makefile` and `makebuild` templates per the instructions, SAM starts the Lambda, but the tests all timeout and my guess is the `lambda.norpc` tag is the issue.

**Comment by x6j8x** [comment]
This is an interesting question.. In the current state IMHO the go-plugin doesn't even support switching to the `provided.al2` runtime. 

`cfn submit` looks for a binary called `handler` hardcoded here (https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/blob/fc208d1da48a82f84cc3741b71bf5e467f0e07ec/python/rpdk/go/codegen.py#L254C58-L254C58), but the new runtime requires the binary/handler to be called `bootstrap`.  So I guess we're out of luck at the moment.

**Comment by msummers-nr** [comment]
@x6j8x I missed that- I'll hack at it and see what I get. Thanks.

**Comment by msummers-nr** [comment]
My issue was a stale indirect dependency on `aws-lambda-go`, updating that to the current `v1.41.0` version works.
