### ISSUE TITLE
Increase buffer for scheduling local reinvocations

### ISSUE THREAD

**Issue by jotompki** [aws-cloudformation/cloudformation-cli-go-plugin#76]
https://github.com/aws-cloudformation/aws-cloudformation-rpdk-java-plugin/pull/188

Similar to this PR, we should guarantee 60 seconds on invocation time to handlers when reinvoking provider handler in the same lambda execution (local reinvoke). 

Change here
https://github.com/aws-cloudformation/aws-cloudformation-rpdk-go-plugin/blob/9266f88bf8a88010811c3c71566bced804b89f1b/cfn/scheduler/scheduler.go#L83

**Comment by brianterry** [comment]
Thank you for submitting the Issue! This was fixed by PR #146.
